export const TAXONOMY: Record<string, string[]> = {
  'Electronics': [
    'Phones & Tablets',
    'Computers & Laptops',
    'Audio & Headphones',
    'Cameras & Photography',
    'TV & Video',
    'Gaming',
    'Components & Parts',
    'Accessories',
  ],
  'Music': [
    'Guitars',
    'Bass',
    'Drums & Percussion',
    'Keyboards & Pianos',
    'Amplifiers',
    'Effects & Pedals',
    'Pro Audio',
    'Accessories',
  ],
  'Home & Garden': [
    'Furniture',
    'Kitchen & Dining',
    'Tools & Hardware',
    'Appliances',
    'Outdoor & Garden',
    'Lighting',
    'Decor',
    'Storage & Organization',
  ],
  'Clothing & Accessories': [
    'Mens',
    'Womens',
    'Kids',
    'Shoes',
    'Bags & Wallets',
    'Activewear',
    'Vintage',
  ],
  'Jewelry & Watches': [
    'Fine Jewelry',
    'Fashion Jewelry',
    'Watches',
    'Loose Stones & Beads',
  ],
  'Sports': [
    'Cycling',
    'Fitness & Gym',
    'Water Sports',
    'Winter Sports',
    'Team Sports',
    'Outdoor & Camping',
    'Running',
    'Racquet Sports',
  ],
  'Books & Media': [
    'Books',
    'Vinyl & Records',
    'CDs & DVDs',
    'Video Games',
    'Magazines',
    'Textbooks',
    'Comics & Graphic Novels',
    'Audiobooks',
  ],
  'Vehicles': [
    'Cars',
    'Motorcycles',
    'Bicycles',
    'Trucks & Vans',
    'Boats',
    'Parts & Accessories',
    'Trailers',
    'Electric Vehicles',
  ],
  'Real Estate': [
    'Apartment',
    'Condo',
    'Townhome',
    'Manufactured',
    'Single Family',
    'Multi-Family',
  ],
  'Collectibles': [
    'Antiques',
    'Art',
    'Coins & Currency',
    'Trading Cards',
    'Memorabilia',
    'Stamps',
    'Vintage Electronics',
  ],
  'Health & Beauty': [
    'Skincare',
    'Makeup',
    'Hair Care',
    'Fragrances',
    'Wellness & Supplements',
  ],
  'Toys & Hobbies': [
    'Action Figures & Dolls',
    'Building Sets',
    'Board Games & Puzzles',
    'RC & Models',
    'Craft Supplies',
  ],
  'Baby & Kids': [
    'Strollers & Car Seats',
    'Clothing',
    'Toys',
    'Furniture & Gear',
    'Feeding & Nursing',
  ],
  'Pet Supplies': [
    'Dogs',
    'Cats',
    'Fish & Aquariums',
    'Small Animals & Birds',
  ],
  'Other': [
    'General',
    'Services',
    'Free Stuff',
    'Wanted',
  ],
};

export function isValidCategory(category: string): boolean {
  return category in TAXONOMY;
}

export function isValidSubcategory(category: string, subcategory: string): boolean {
  if (!isValidCategory(category)) return false;
  return TAXONOMY[category].includes(subcategory);
}
